-- Creacion de tablas
CREATE TABLE Gerente (
    idGerente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descGerente VARCHAR2(100),
    fechaRegistro DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Condicion (
    idCondicion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descCondicion VARCHAR2(100),
    fechaRegistro DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Provincia (
    idProvincia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descProvincia VARCHAR2(100),
    fechaRegistro DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Sede (
    idSede NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descSede VARCHAR2(100),
    fechaRegistro DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Distrito (
    idDistrito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idProvincia NUMBER,
    descDistrito VARCHAR2(100),
    fechaRegistro DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (idProvincia) REFERENCES Provincia(idProvincia)
);


CREATE TABLE Hospital (
    idHospital NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idDistrito NUMBER,
    Nombre VARCHAR2(100),
    Antiguedad NUMBER,
    Area NUMBER,
    idSede NUMBER,
    idGerente NUMBER,
    idCondicion NUMBER,
    fechaRegistro DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (idDistrito) REFERENCES Distrito(idDistrito),
    FOREIGN KEY (idSede) REFERENCES Sede(idSede),
    FOREIGN KEY (idGerente) REFERENCES Gerente(idGerente),
    FOREIGN KEY (idCondicion) REFERENCES Condicion(idCondicion)
);


---Insert en las tablas
INSERT INTO Gerente (descGerente) VALUES ('Jorge Juan Fuster');
INSERT INTO Gerente (descGerente) VALUES ('Demetrio Abellan');
INSERT INTO Gerente (descGerente) VALUES ('Saul Ferrando');
INSERT INTO Gerente (descGerente) VALUES ('Josep Trujillo');
INSERT INTO Gerente (descGerente) VALUES ('Victoria Palacio');
INSERT INTO Gerente (descGerente) VALUES ('Jose Enrique Rueda');
INSERT INTO Gerente (descGerente) VALUES ('Yanira Gallego');
INSERT INTO Gerente (descGerente) VALUES ('Marcelino Paz');
INSERT INTO Gerente (descGerente) VALUES ('Alma Salazar');
INSERT INTO Gerente (descGerente) VALUES ('Luis Enrique Pallares');

INSERT INTO Condicion (descCondicion) VALUES ('Activo');
INSERT INTO Condicion (descCondicion) VALUES ('Inactivo');

INSERT INTO Provincia (descProvincia) VALUES ('LIMA');
INSERT INTO Provincia (descProvincia) VALUES ('BARRANCA');
INSERT INTO Provincia (descProvincia) VALUES ('CAJATAMBO');
INSERT INTO Provincia (descProvincia) VALUES ('CANTA');
INSERT INTO Provincia (descProvincia) VALUES ('CAÑETE');
INSERT INTO Provincia (descProvincia) VALUES ('HUARAL');
INSERT INTO Provincia (descProvincia) VALUES ('HUAROCHIRI');
INSERT INTO Provincia (descProvincia) VALUES ('HUAURA');
INSERT INTO Provincia (descProvincia) VALUES ('OYON');
INSERT INTO Provincia (descProvincia) VALUES ('YAUYOS');

INSERT INTO Sede (descSede) VALUES ('Sede Central');
INSERT INTO Sede (descSede) VALUES ('Sede Regional');
INSERT INTO Sede (descSede) VALUES ('Sede Provincial');

INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'ANCON');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'ATE');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'BARRANCO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'BREÑA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'CARABAYLLO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'CHORRILLOS');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'COMAS');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'EL AGUSTINO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'INDEPENDENCIA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'JESUS MARIA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'LA MOLINA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'LA VICTORIA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'LINCE');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'LOS OLIVOS');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'MIRAFLORES');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'PACHACAMAC');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'PUENTE PIEDRA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'RIMAC');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SAN BORJA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SAN ISIDRO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SAN JUAN DE LURIGANCHO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SAN JUAN DE MIRAFLORES');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SAN LUIS');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SAN MARTIN DE PORRES');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SAN MIGUEL');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SANTA ANITA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SANTIAGO DE SURCO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'SURQUILLO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'VILLA EL SALVADOR');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (1, 'VILLA MARIA DEL TRIUNFO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (2, 'PARAMONGA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (2, 'PATIVILCA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (2, 'SUPE');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (3, 'COPA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (3, 'GORGOR');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (3, 'HUANCAPON');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (3, 'MANAS');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (4, 'ARAHUAY');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (4, 'HUAMANTANGA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (4, 'HUAROS');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (4, 'LACHAQUI');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (5, 'SAN VICENTE DE CAÑETE');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (5, 'ASIA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (5, 'CALANGO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (5, 'CERRO AZUL');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (5, 'CHILCA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (6, 'CHANCAY');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (6, 'AUCALLAMA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (7, 'MATUCANA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (7, 'ANTIOQUIA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (8, 'HUACHO');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (8, 'SAYAN');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (8, 'VEGUETA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (9, 'ANDAJES');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (9, 'COCHAMARCA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (10, 'AYAUCA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (10, 'HUANCAYA');
INSERT INTO Distrito (idProvincia, descDistrito) VALUES (10, 'TANTA');

